2025-08-13 23:37:04,381 INFO: GitLab Analytics Hub startup [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:32]
2025-08-13 23:37:04,382 INFO: --- PATH DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:35]
2025-08-13 23:37:04,382 INFO: App Root Path: D:\Documents\Code\gitlab-automation-suite\app [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:36]
2025-08-13 23:37:04,382 INFO: App Template Folder: templates [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:37]
2025-08-13 23:37:04,383 INFO: Full Template Path: D:\Documents\Code\gitlab-automation-suite\app\templates [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:38]
2025-08-13 23:37:04,384 INFO: --- END PATH DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:39]
2025-08-13 23:37:05,337 INFO: --- BLUEPRINT DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:46]
2025-08-13 23:37:05,338 INFO: Registered Blueprint: 'main' [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:48]
2025-08-13 23:37:05,339 INFO:   - Blueprint Template Folder: ../templates [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:49]
2025-08-13 23:37:05,340 INFO: --- END BLUEPRINT DEBUGGING --- [in D:\Documents\Code\gitlab-automation-suite\app\__init__.py:50]
2025-08-13 23:38:12,709 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:38:19,321 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:38:46,636 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:38:48,590 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:38:56,784 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:39:00,154 ERROR: Could not process epic iid 18 in group 2: 'GroupEpic' object has no attribute 'epics' [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:222]
2025-08-13 23:39:00,155 INFO: Found 2 unique issues for epic #18 and its descendants. [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:231]
2025-08-13 23:39:23,136 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:39:26,730 ERROR: Could not process epic iid 18 in group 2: 'GroupEpic' object has no attribute 'epics' [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:222]
2025-08-13 23:39:26,731 INFO: Found 2 unique issues for epic #18 and its descendants. [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:231]
2025-08-13 23:39:55,146 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:40:02,141 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:40:06,643 ERROR: Could not process epic iid 368 in group 2: 'GroupEpic' object has no attribute 'epics' [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:222]
2025-08-13 23:40:06,645 INFO: Found 21 unique issues for epic #368 and its descendants. [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:231]
2025-08-13 23:40:21,576 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:40:23,272 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:40:29,194 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:40:32,262 ERROR: Could not process epic iid 18 in group 2: 'GroupEpic' object has no attribute 'epics' [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:222]
2025-08-13 23:40:32,264 INFO: Found 2 unique issues for epic #18 and its descendants. [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:231]
2025-08-13 23:41:12,676 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:41:16,286 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:41:18,106 ERROR: Could not process epic iid 18 in group 2623: 'GroupEpic' object has no attribute 'epics' [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:222]
2025-08-13 23:41:18,107 INFO: Found 35 unique issues for epic #18 and its descendants. [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:231]
2025-08-13 23:43:20,019 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:43:21,261 ERROR: Could not process epic iid 18 in group 2623: 'GroupEpic' object has no attribute 'epics' [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:222]
2025-08-13 23:43:21,262 INFO: Found 35 unique issues for epic #18 and its descendants. [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:231]
2025-08-13 23:45:56,591 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:46:21,487 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:46:33,784 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:46:41,209 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:46:43,515 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:46:54,213 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:46:58,741 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:48:16,330 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-13 23:48:18,418 ERROR: Could not process epic iid 18 in group 2623: 'GroupEpic' object has no attribute 'epics' [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:222]
2025-08-13 23:48:18,419 INFO: Found 35 unique issues for epic #18 and its descendants. [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:231]
2025-08-14 00:18:52,090 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-14 00:19:05,726 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-14 00:19:15,872 INFO: Successfully connected to GitLab at https://emu.hinagro.com [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:27]
2025-08-14 00:19:15,873 INFO: Generating Defect Trend Report for 6 months. [in D:\Documents\Code\gitlab-automation-suite\app\main\logic.py:167]
2025-08-14 00:19:20,002 INFO: Fetched ALL 186 issues with filters: {'created_after': '2025-02-01', 'created_before': '2025-03-01', 'labels': 'type::bug', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
2025-08-14 00:19:20,735 INFO: Fetched ALL 14 issues with filters: {'created_after': '2025-02-01', 'created_before': '2025-03-01', 'labels': 'found-post-release', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
2025-08-14 00:19:21,188 INFO: Fetched ALL 3 issues with filters: {'created_after': '2025-02-01', 'created_before': '2025-03-01', 'labels': 'production-issue', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
2025-08-14 00:19:28,756 INFO: Fetched ALL 426 issues with filters: {'created_after': '2025-02-01', 'created_before': '2025-03-01', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
2025-08-14 00:19:31,306 INFO: Fetched ALL 157 issues with filters: {'created_after': '2025-03-01', 'created_before': '2025-04-01', 'labels': 'type::bug', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
2025-08-14 00:19:31,881 INFO: Fetched ALL 14 issues with filters: {'created_after': '2025-03-01', 'created_before': '2025-04-01', 'labels': 'found-post-release', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
2025-08-14 00:19:32,303 INFO: Fetched ALL 6 issues with filters: {'created_after': '2025-03-01', 'created_before': '2025-04-01', 'labels': 'production-issue', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
2025-08-14 00:19:37,755 INFO: Fetched ALL 395 issues with filters: {'created_after': '2025-03-01', 'created_before': '2025-04-01', 'all': True, 'include_subgroups': True} [in D:\Documents\Code\gitlab-automation-suite\app\main\services.py:279]
